using UnityEngine;

public class DebugGameObject : MonoBehaviour
{
    // Bool to load data in the 'UniverseRunner' instance using the JSON files generated by the StartLocation UI
    // If set to FALSE, the ship will be initialized using user input data in its scriptable objects from the UNITY_EDITOR
    public bool loadShipDataFromUIDiskFile=false;

    void Awake()
    {
        DontDestroyOnLoad(this.gameObject);
    }
}
